### ISSUE TITLE
App Store guidlines

### ISSUE THREAD

**Issue by TofPlay** [crashoverride777/SwiftyRate#2]
Hi,
> Apple has updated the app store guidlines and it seems that with iOS 11 it is no longer allowed to show custom review prompts.

For my information can you give me the rule on the app store guidlines for that?

**Comment by TofPlay** [comment]
Found it :-) 
1.1.7 App Store Reviews

**Comment by crashoverride777** [comment]
Hey, thanks for you comment.

Best regards
